### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by somnuk-wk** [icflorescu/iisexpress-proxy#1]
### Version 1.0.1

Crash when request to `10.211.55.3:4000` on Windows 10.

``` bat
C:\Users\wk>iisexpress-proxy 25840 to 4000
IIS Express Proxy 1.0.1
Proxying localhost:25840 to:
- Ethernet: 10.211.55.3:4000
Listening... [ press Control-C to exit ]
C:\Users\wk\AppData\Roaming\npm\node_modules\iisexpress-proxy\node_modules\http-proxy\lib\http-proxy\index.js:119
    throw err;
          ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

**Comment by somnuk-wk** [comment]
Ok, it work when I run command as administrator.

**Comment by srmrco** [comment]
Admin privileges didn't work for me in Windows 10.

```
PS C:\WINDOWS\system32> iisexpress-proxy localhost:60100 to 30000
IIS Express Proxy 1.1.8
Proxying http://localhost:60100 to network interfaces:
        vEthernet (Internal Virtual Switch): 192.168.137.1:30000
        Ethernet: 192.168.1.12:30000
        Wi-Fi: 192.168.2.21:30000
Listening... [press Control-C to exit]
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
Listening... [press Control-C to exit]
...
```

I switched off my antivirus and windows firewall. Trying to figure out what else might be preventing the connection.

**Comment by srmrco** [comment]
Finally I was able to get around this issue. It turned out that IIS Express was listening on IPv6 port. 

[Details are here](http://programmingflow.com/2017/02/25/iis-express-on-external-ip.html)

**Comment by icflorescu** [comment]
@srmrco - if you have time to spare and are willing to make a PR, I'll be happy to include it. AFAIK, [http-proxy](https://github.com/nodejitsu/node-http-proxy), the core of iisexpress-proxy, can be made to work with IPv6 as well. See more info [here](https://github.com/nodejitsu/node-http-proxy/pull/558).
