### ISSUE TITLE
Offline installation fails - npmbox npmunbox

### ISSUE THREAD

**Issue by stevzie** [icflorescu/iisexpress-proxy#10]
I receive the following trying to install to a system with no internet connection.:
c:>npmunbox -v -g iisexpress-proxy.npmbox

Unboxing iisexpress-proxy.npmbox...
  Unpacking iisexpress-proxy.npmbox...
  Installing iisexpress-proxy...
npm verb request uri https://registry.npmjs.org/iisexpress-proxy
npm verb request no auth needed
npm info attempt registry request try #1 at 11:53:50 AM
npm verb request id e98fff2ab2b30d40
npm http request GET https://registry.npmjs.org/iisexpress-proxy
An error occurred while installing iisexpress-proxy.
iisexpress-proxy was not installed.
{ [Error: connect ETIMEDOUT 151.101.44.162:443]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '151.101.44.162',
  port: 443 }
  Done.

**Comment by digital-synapse** [comment]
works fine for me. tested on windows 10 in airplane mode using node v6.10.1 LTS

```
E:\dev\tests>npmunbox iisexpress-proxy.npmbox -g

Unboxing iisexpress-proxy.npmbox...
  Unpacking iisexpress-proxy.npmbox...
  Installing iisexpress-proxy...
  Done.
```

**Comment by icflorescu** [comment]
Thanks again, @digital-synapse.

I'll be closing this, since it's clearly not an issue with `iisexpress-proxy`.

**Comment by 811722066** [comment]
How to solve??
