### ISSUE TITLE
Redirects to the IIS server should be transformed

### ISSUE THREAD

**Issue by fizker** [icflorescu/iisexpress-proxy#13]
When the IIS express server does a redirect (status 301, 302, 303, 307, 308), the same port-redirection should be applied.

For example, I started the proxy with `iisexpress-proxy 53856 to 8079`. When IIS express then sends a `location:http://localhost:53856/login/` header, it should be rewritten to `location:http://<request-host>:8079/login/`, because the original URL will by definition not work.

**Comment by icflorescu** [comment]
I seldom use `iisexpress-proxy` in my work nowadays, but – for the benefit of community – I'll gladly accept a PR addressing this ;-)

**Comment by dylanvdmerwe** [comment]
What do you use instead?

**Comment by icflorescu** [comment]
@dylanvdmerwe I've completely switched away from .NET/IIS/Windows to Node.js/Express/React on Linux/macOS, so I don't have to deal with such workarounds nowadays.

That being said, I'm still maintaining `iisexpress-proxy`, but only based on meaningful PRs from the community of users still using it.

I'm also looking for a "co-maintainer", so, anyone willing and up to it, please feel free to drop me a line.

I guess I should post this as an update in the README too.

**Comment by rsheptolut** [comment]
Thanks @alancnet! And @fizker for reporting the bug!

My ASP.NET Core local debug auth flow was completely wrecked for almost a month, had to reset it manually each startup. Short reason: cookies for localhost and 192.168.123.123 are different. Found time today to finally figure out what's wrong with it. Was initially blaming ASP.NET Core for somehow rewriting the request from an IP to `localhost` and took me half a day to remember I'm using `iisexpress-proxy` and it might rewrite stuff as well. `1.3.0` was working fine and the issue started happening after updating to `1.4.5`. But what a pleasant feeling to simply update a package (to `1.4.9`) and find that it fixes your problem! Just like that, my IP is not being changed to `localhost` against my will anymore. Yay!

And thanks to @icflorescu for a useful tool. Some of us still have to "deal with such workarounds" 😀
