### ISSUE TITLE
SignalR not working with proxy.

### ISSUE THREAD

**Issue by oguzhantopcu** [icflorescu/iisexpress-proxy#18]
WebSocket connection to 'ws://guest:5000/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=2sHfR1yy9nfjoohNtgQy2uUIFHvIsSkKJMf5vBWPwUhm4yFGjvmrfwoFV%2BME5LjVCY7JziJjNjneWF3Z3QyLyIY6tSeCwhtgxE%2FeiInNhgB8%2BSVzRPsEQE4xa6SE%2Fo8ipbs9cyXiDI6R7%2BpbNBXYXTE1%2BGZOqaZrfFHPBVW7YhI%3D&connectionData=%5B%7B%22name%22%3A%22scannerhub%22%7D%5D&tid=5' failed: Connection closed before receiving a handshake response

This is the error I receive in a page that have SignalR client. Probably it is not supporting web sockets.

**Comment by dylanvdmerwe** [comment]
SignalR will revert back to ServerSent Events which will work.

**Comment by oguzhantopcu** [comment]
It was not working but I am not sure that was the root cause, I will check and return back to you.

**Comment by icflorescu** [comment]
Unfortunately I'm not using IIS / .NET / Windows in my work anymore, but... could anyone please test with v.1.4.0 and see if this is still an issue?

**Comment by icflorescu** [comment]
This should work starting with `v1.4.0`.
