### ISSUE TITLE
AWS EC2

### ISSUE THREAD

**Issue by plutext** [icflorescu/iisexpress-proxy#22]
This works beautifully on my dev laptop, thanks, but how to use it on a Win Server 2016 EC2 instance?

It sees the private IP address, but I need it to listen to the public IP address.

So something like iisexpress-proxy 51123 to publicip:3000

Inside the instance, ipconfig does not show the public ip address.

**Comment by icflorescu** [comment]
Sorry for the late reply, but I have absolutely no idea how to solve this not can I test in on an EC2 instance.

BTW, if you're interested and still using `iisexpress-proxy`, would you be interested in becoming a co-maintainer?

**Comment by icflorescu** [comment]
I have no way of testing this and since it's outside the original scope of the project, I'm afraid I'll have to close it. Anyone able to address this - please reopen with a PR.
