### ISSUE TITLE
Swagger doesn't work properly with the plugin

### ISSUE THREAD

**Issue by tkleobit** [icflorescu/iisexpress-proxy#24]
The "forwarding" works just fine, but in  case of usage with Swagger - swagger has issues connecting. Usually returns 
```
{
  "error": "no response from server"
}
```
in case of Json
Despite that, if you call the methods via postman, on the external IP, it works just fine.

**Comment by icflorescu** [comment]
Sorry for the late reply, but I have absolutely no idea how to solve this.

BTW, if you're interested and still using `iisexpress-proxy`, would you be interested in becoming a co-maintainer?

**Comment by icflorescu** [comment]
Not an issue, then. I'll close due to inactivity.
