### ISSUE TITLE
instead of ip, name based urls

### ISSUE THREAD

**Issue by blackholeearth** [icflorescu/iisexpress-proxy#28]
my ip changes.

can't i use my pcname instead? thnx?

**Comment by digital-synapse** [comment]
Setting a static IP address for your machine is probably a more reliable
way to prevent the address from changing. IMO

**Comment by blackholeearth** [comment]
It is a work pc. They have firewall if i try to set static ip. it bans me from network.

 Its not an option.

**Comment by icflorescu** [comment]
Any idea on how this could be addressed? I seldom use Windows myself nowadays, so I can't really test new features/ideas, but I'm fully open to PRs that would benefit the community...

**Comment by LucFeron** [comment]
This works just fine with dynamic IP addresses. If you start the IIS proxy and you call http://PC-name:port/ from another PC the webpage loads.
