### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by luisgizirian** [icflorescu/iisexpress-proxy#3]
Hi! Been using it successfully for a while. What about sites running on SSL? Is it possible to bridge those?

**Comment by icflorescu** [comment]
Bridging to sites running on SSL, as in proxying https://www.bloomberg.com:443 to http://localhost:3000?
I think it will, as soon as I'll have a chance to deploy a new version.
Hopefully in a couple of hours or so... ;-)

Note that you won't be able to proxy **to** http**s**://localhost, though. That would involve having a local SSL certificate and would be well out of the scope of this project, anyway.

**Comment by icflorescu** [comment]
Just finished pushing the repo, so you make sure to update your npm installation and see if it works for you. You'll have to use it like this:
`iisexpress-proxy https://secure-domain.com:443 to 5000`
or
`iisexpress-proxy https://192.168.1.110:443 to 5000`

It's important not to omit the `https://` part.

**Comment by luisgizirian** [comment]
Thanks @icflorescu :)
