### ISSUE TITLE
Url not matching regex

### ISSUE THREAD

**Issue by IavorOrlyov** [icflorescu/iisexpress-proxy#35]
After I have installed iis-express following error is thrown:

iisexpress-proxy https://localhost:44355/ to 3000
IIS Express Proxy 1.7.3
C:\Users\{username}\AppData\Roaming\npm\node_modules\iisexpress-proxy\index.js:39
var targetMatch = args._[4].match(urlRegExp);
                            ^

TypeError: args._[4].match is not a function
    at Object.<anonymous> (C:\Users\{username}\AppData\Roaming\npm\node_modules\iisexpress-proxy\index.js:39:29)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by icflorescu** [comment]
Thanks, will look into it ASAP; it's a regression in `v1.7.x`.
Will let you know here as soon as it's fixed.
Meanwhile you can downgrade to `v1.6.2`.

**Comment by IavorOrlyov** [comment]
Awesome work. Keep it up!



On Tuesday, February 15, 2022, 9:27 PM, Ionut-Cristian Florescu ***@***.***> wrote:




Thanks, will look into it ASAP; it's a regression in v1.7.x.
Will let you know here as soon as it's fixed.
Meanwhile you can downgrade to v1.6.2.

**Comment by icflorescu** [comment]
Should be fixed in `v.1.7.4`. Sorry for the inconvenience.

**Comment by icflorescu** [comment]
> Awesome work. Keep it up!

🙏

**Comment by formerlymisterhenson** [comment]
Maybe same thing missing here:
const sourceMatch = args._[2].match(urlRegExp);
const sourceMatch = String(args._[2]).match(urlRegExp);

Because IIS Express Proxy 1.7.4 is giving me
args._[2].match is not a function

: Awesome work. 
signed.
