### ISSUE TITLE
Url not matching regex ^2

### ISSUE THREAD

**Issue by formerlymisterhenson** [icflorescu/iisexpress-proxy#36]
In addition to #35 - maybe same thing missing here:
```
const sourceMatch = args._[2].match(urlRegExp);
```
so perhaps?
```
const sourceMatch = String(args._[2]).match(urlRegExp);
```

Because IIS Express Proxy 1.7.4 is giving me
args._[2].match is not a function

: Awesome work. 
signed.

**Comment by icflorescu** [comment]
Thanks! Fixed in `v1.7.5`.
