### ISSUE TITLE
Great utility

### ISSUE THREAD

**Issue by robeverett** [icflorescu/iisexpress-proxy#40]
However, you would earn greater respect from a far greater percentage of developers if you were to leave your anti Russian political diatribe out of GitHub !

**Comment by icflorescu** [comment]
Hey Rob,

Thank you for the kind words!

However, I fail to understand what you mean by anti-Russian political diatribe. I usually don't have time, energy or interest for politics and I find diatribes to be counter-productive. And I most certainly dislike xenophobic displays (as in people holding prejudice against other people based on citizenship).

If you were referring to the statement/plea in the README related to the [2022 Russian invasion of Ukraine](https://en.wikipedia.org/wiki/2022_Russian_invasion_of_Ukraine), I'm sorry if your feelings were hurt - that was not my intention. 

I happen to have friends/connections in both Ukraine and Russia and they were all affected by the events, to say the least. Some of them were involved in building great open-source projects. Some of them still do. Some of them are not around anymore.

Not acknowledging such facts would be willful ignorance.

Many companies, organizations and communities, such as **GitHub** (see "[Our response to the war in Ukraine](https://github.blog/2022-03-02-our-response-to-the-war-in-ukraine/)", **[Svelte](https://svelte.dev/)**, **[Netlify.io](https://www.netlify.com/blog/we-stand-with-ukraine/)**, etc., chose to display similar pleas and/or statements condemning the acts of violence, not people based on their citizenship.
