### ISSUE TITLE
Please mention in the read-me that projects with integrated Windows authentication aren't supported

### ISSUE THREAD

**Issue by mklement0** [icflorescu/iisexpress-proxy#5]
First things first: thanks for a great utility.

It seems that projects that use integrated Windows authentication aren't supported by `iisexpress-proxy` -  I get a "401.2 Unauthorized" error complaining about  "invalid authentication headers".

Not sure if supporting such projects is even an option or on your roadmap, but it would be helpful if you documented the limitation in `README.md`.

**Comment by icflorescu** [comment]
Thank you the kind words.

I have no idea on how to possibly implement this, nor any chance to test such a scenario at the moment, but if you have any idea, please feel free to make a PR.

Meanwhile, I'll just add a quick reference to this issue in the `README.md`.

**Comment by icflorescu** [comment]
This is now in the `README.md`.

**Comment by mklement0** [comment]
I appreciate it, thanks.

As for testing: In VS2015, I created an ASP.NET Web Application; on the 2nd creation-dialog page, if you choose `MVC`, and then click `Change Authentication` choose option `Windows Authentication`, you'll get a project that requires valid Windows credentials to access the site.

You're implicitly authenticated on the dev machine, but on external access you should be prompted for credentials in a pop-up dialog box - this is where proxying currently throws the Unauthorized error instead.

Unfortunately, I don't know how or even if the problem can be solved.

**Comment by byoigres** [comment]
I have the exactly same problem when I was using [browser sync](https://www.browsersync.io/) and I ended here thinking that this were to solve my problem until I read that this does not work with windows authentication. What a shame, I'm reading a tons of articles about this and I'm not getting closer to a solution.

**Comment by Mensana88** [comment]
In the end, this [blog post](http://www.hanselman.com/blog/WorkingWithSSLAtDevelopmentTimeIsEasierWithIISExpress.aspx) by Scott Hanselman helped me solve the problem. It is not as elegant as Ionut's solution, but it works with Windows Authentication.
