### ISSUE TITLE
Using IIS Express with Internet Connection Sharing

### ISSUE THREAD

**Issue by jeremy-holt** [icflorescu/iisexpress-proxy#6]
Hi,

Unfortunately, I am obliged to use ICS to share my internet connection.

With ICS enabled, I am unable to run IIS Express - I get this error:

```
"c:\Program Files\IIS Express\iisexpress" /port:63293 /path:"C:\Visual Studio Projects\Cornhouse.PepperFactory\Cornhouse.PepperFactory.UI"
Copied template config file 'c:\Program Files\IIS Express\AppServer\applicationhost.config' to 'D:\Temp\iisexpress\applicationhost2016423131125484.config'
Updated configuration file 'D:\Temp\iisexpress\applicationhost2016423131125484.config' with given cmd line info.
Starting IIS Express ...
Failed to register URL "http://localhost:63293/" for site "Development Web Site" application "/". Error description: Access is denied. (0x80070005)
Registration completed
Unable to start iisexpress.

Access is denied.
For more information about the error, run iisexpress.exe with the tracing switch enabled (/trace:error).
```

Is there any way that iisexpress-proxy can help me with this?

My knowldege of networking is about zilch!

Many thanks
Jeremy

**Comment by icflorescu** [comment]
Sorry, but I haven't used it in that scenario, so there's no way for me to tell.

But, since this package is doing over 700 downloads a month on npm, I'll mark this issue as "question" and hopefully one of the users will be able to provide a useful answer.
